import type { ThemeTemplates } from '../types.js';
import type { Bell, RuneArchetype, ContradictionType } from '../../types/index.js';

/**
 * Casefile (Modern Procedural) — 100 alibi templates + expanded interrogation banks.
 *
 * Voice: Contemporary procedural English. Terse cop-speak to nervous rambling
 * to corporate jargon. Modern references (phones, elevators, security cameras).
 */

const casefileTemplates: ThemeTemplates = {
  // ─── Display names ─────────────────────────────────────────
  runeNames: {
    oaths: { name: 'Timeline', description: 'CCTV timestamps, access logs, clock records' },
    roads: { name: 'Transit Log', description: 'Elevator records, badge swipes, corridors' },
    relics: { name: 'Item Registry', description: 'Keycards, devices, personal effects' },
    skies: { name: 'Scene Analysis', description: 'Environmental readings, sensor data' },
  } satisfies Record<RuneArchetype, { name: string; description: string }>,

  bellNames: {
    0: '8 AM',
    1: '9 AM',
    2: '10 AM',
    3: '11 AM',
    4: '12 PM',
    5: '1 PM',
  } satisfies Record<Bell, string>,

  bellLabelsShort: {
    0: '8a', 1: '9a', 2: '10a', 3: '11a', 4: '12p', 5: '1p',
  } satisfies Record<Bell, string>,

  contradictionLabels: {
    time: 'Timeline mismatch',
    movement: 'Access violation',
    object: 'Item discrepancy',
    environment: 'Scene anomaly',
  } satisfies Record<ContradictionType, string>,

  // ─── 100 Alibi Templates ──────────────────────────────────
  alibiTemplates: [
    // --- Terse / Report-style (1–10) ---
    '{bell1}. Arrived at {loc1}. Stayed through {bell2}. Ran inventory. Nobody came in. Nothing flagged.',
    'I was at {loc1} from {bell1} until {bell2}. Standard shift. Nothing to report.',
    '{loc1}. {bell1} to {bell2}. That\'s it.',
    'Clocked in at {loc1} at {bell1}. Clocked out after {bell2}. Check the logs.',
    'I was at {loc1}, {bell1} through {bell2}. Did my job. Went home.',
    '{bell1}: {loc1}. {bell2}: still {loc1}. Nothing happened.',
    'At {loc1} from {bell1} to {bell2}. Routine maintenance. No incidents.',
    'I was posted at {loc1}. {bell1} to {bell2}. Quiet shift.',
    '{loc1}, {bell1} to {bell2}. Paperwork. That\'s the whole story.',
    'Stationed at {loc1} from {bell1}. Didn\'t move till {bell2}. That\'s my statement.',

    // --- Nervous / Over-explaining (11–20) ---
    'So I was at {loc1}, right? I got there around {bell1} — maybe a minute or two after, the elevator was slow — and I just stayed there until {bell2}. I mean, I didn\'t leave. You can check the badge logs.',
    'Look, I was at {loc1}. Got there at {bell1}. Stayed till {bell2}. I know that sounds vague but it\'s the truth. I wasn\'t doing anything wrong.',
    'I was definitely at {loc1}. {bell1}. I remember because I checked my phone. And I was still there at {bell2}. I\'m positive.',
    'Okay so here\'s the thing — I was at {loc1} from {bell1}. I didn\'t leave. I was there through {bell2}. I know, I know, nobody saw me, but that\'s where I was.',
    'I was at {loc1}. I got there at {bell1}. I stayed until {bell2}. I know I keep saying the same thing but that\'s because it\'s true.',
    'Yeah, um, {loc1}. From about {bell1}. I was just... sitting there, mostly. Until {bell2}. Is that a problem?',
    'I was at {loc1}, I swear. From {bell1} to {bell2}. I wasn\'t trying to avoid anyone, I just had work to do there.',
    'Can I just — I was at {loc1}. {bell1} to {bell2}. I had my headphones on. I didn\'t hear anything. I didn\'t see anything.',
    'I know this looks weird, but {loc1}, {bell1} through {bell2}. I was on a call most of the time. A personal call. That\'s all.',
    'I don\'t know what you want me to say. I was at {loc1}. Got there at {bell1}, left after {bell2}. That\'s my day.',

    // --- Corporate / Jargon (21–30) ---
    'I was facilitating a cross-departmental audit at {loc1} from {bell1} through {bell2}. The scope was fairly contained.',
    'Per my calendar, I had a block at {loc1} from {bell1} to {bell2}. Status: completed. No action items.',
    'I was at {loc1} for a scheduled review. Timeline: {bell1} to {bell2}. All deliverables were on track.',
    'My availability was blocked for {loc1} from {bell1} through {bell2}. I was conducting a compliance check.',
    'I was on-site at {loc1}, {bell1} to {bell2}, executing a routine process evaluation.',
    'I had a standing commitment at {loc1} from {bell1}. The session ran through {bell2}. Standard operating procedure.',
    'I was engaged in inventory reconciliation at {loc1}. Start time: {bell1}. End time: {bell2}.',
    'Per the assignment log, I was allocated to {loc1} from {bell1} to {bell2}. I executed accordingly.',
    'My schedule had me at {loc1} from {bell1} to {bell2} for a facilities assessment. The walkthrough was thorough.',
    'I was at {loc1} from {bell1} through {bell2}, addressing a backlog of maintenance tickets.',

    // --- Casual / Conversational (31–42) ---
    'Yeah, I was at {loc1}. Showed up around {bell1}, hung around till past {bell2}. Pretty chill. Nothing worth mentioning.',
    'I was at {loc1} from {bell1}. Didn\'t really do much. Still there at {bell2}.',
    'Hung out at {loc1}, {bell1} to {bell2}. Had my coffee. Did some work. That\'s about it.',
    'I was at {loc1}. What time? {bell1}. When did I leave? After {bell2}. Anything else?',
    'Spent the morning at {loc1}. Got there at {bell1}, left around {bell2}. Normal day.',
    'I was just at {loc1}, from {bell1}. Time kind of flew. Before I knew it, {bell2} had passed.',
    'Was at {loc1}. Got there at {bell1}. Stayed through {bell2}. Nothing exciting.',
    'I parked myself at {loc1} around {bell1}. Didn\'t move till {bell2}. Lazy morning.',
    '{loc1}. {bell1} to {bell2}. I was on my phone half the time, honestly.',
    'I was in {loc1} from {bell1}. Had some stuff to take care of. Wrapped up around {bell2}.',
    'Yeah, {loc1}. From like {bell1} till after {bell2}. Just working.',
    'I was at {loc1}. Got there around {bell1}. Still there when {bell2} rolled around.',

    // --- Hostile / Defensive (43–52) ---
    'I\'m not obligated to answer that, but fine. {loc1}. {bell1} to {bell2}. Happy? Can I go now?',
    'How many times do I have to say it? {loc1}. {bell1}. {bell2}. We done?',
    '{loc1}, {bell1} to {bell2}. I don\'t know what else you want from me.',
    'I was at {loc1}. From {bell1} to {bell2}. If you don\'t believe me, pull the security footage.',
    'This is harassment. But for the record: {loc1}. {bell1} through {bell2}.',
    'I\'ve already told you where I was. {loc1}. {bell1} to {bell2}. Next question.',
    'Before you start — I know how it looks, but I was at {loc1} the entire time. {bell1} to {bell2}. Ask the security camera.',
    'I don\'t appreciate the implication. {loc1}. {bell1}. {bell2}. Check the access logs if you don\'t trust me.',
    '{loc1}, from {bell1} till {bell2}. I don\'t see why this is anyone\'s business.',
    'Talk to my lawyer if you want details. But off the record: {loc1}. {bell1} to {bell2}.',

    // --- Exhausted / Weary (53–60) ---
    'Look, I\'d been on since midnight. By {bell1} I was at {loc1} trying to stay awake. I didn\'t move until {bell2}.',
    'I was dead on my feet at {loc1}. Got there at {bell1}. Didn\'t have the energy to leave until {bell2}.',
    '{loc1}, {bell1} to {bell2}. I was running on coffee and stubbornness. That\'s the whole shift.',
    'I barely remember. {loc1}. {bell1}. {bell2}. I was so tired everything blurs together.',
    'Long day. I was at {loc1} from {bell1} through {bell2}. The vending machine coffee was terrible.',
    'I was at {loc1}. When? {bell1}. When did I leave? {bell2}, I think. I was exhausted.',
    '{bell1} found me at {loc1}, half asleep in a chair. I was still there at {bell2}.',
    'I was at {loc1} from {bell1}. Barely functional. Left after {bell2} when my replacement showed.',

    // --- Tech-savvy / Digital (61–70) ---
    'I was at {loc1} from {bell1} — you can pull my Slack status, it was set to DND. Didn\'t leave until past {bell2}.',
    'My laptop connected to the {loc1} WiFi at {bell1}. It didn\'t disconnect until after {bell2}. The logs don\'t lie.',
    'I was at {loc1}. Badge swipe at {bell1}. Next swipe out: {bell2}. Digital trail confirms it.',
    'GPS on my phone would show me at {loc1} from {bell1} to {bell2}. You\'re welcome to subpoena it.',
    'I was at {loc1}, {bell1} to {bell2}. My fitness tracker logged zero steps during that window.',
    'Check the building\'s access control system. I badged into {loc1} at {bell1} and out after {bell2}.',
    'I was at {loc1}. My Teams status went green at {bell1} and I didn\'t go offline until {bell2}.',
    'I was at {loc1} from {bell1} through {bell2}. My sent emails are timestamped if you need proof.',
    'The security system logged me at {loc1}, {bell1} entry. I didn\'t badge out until after {bell2}.',
    'I was at {loc1}. My phone was charging there from {bell1}. I picked it up at {bell2}. Screen time confirms.',

    // --- Journey / Movement (71–80) ---
    'Left {loc1} at {bell1}. Took the south stairwell because the elevator was out again. Got to {loc2} by {bell2}.',
    'I walked from {loc1} to {loc2}. Left at {bell1}, arrived at {bell2}. It\'s a longer walk than people think.',
    'I was heading from {loc1} to {loc2}. Started at {bell1}. Got there at {bell2}. Took the back hallway.',
    '{bell1}: left {loc1}. {bell2}: arrived at {loc2}. Route: main corridor, east elevator.',
    'I went from {loc1} to {loc2}, {bell1} to {bell2}. Stopped to get water on the way.',
    'Departed {loc1} at {bell1}. Reached {loc2} at {bell2}. The hallway was empty.',
    'Traveled from {loc1} to {loc2}, {bell1} to {bell2}. Had to take the long way around.',
    'I left {loc1} at {bell1} heading for {loc2}. Got there at {bell2}. Badge swipe would confirm.',
    'I was in transit from {loc1} to {loc2}. {bell1} departure, {bell2} arrival. Standard route.',
    'From {loc1} at {bell1}. Walked to {loc2}. Arrived {bell2}. The fire door on 3 was propped open.',

    // --- Fragmented / Distracted (81–88) ---
    'I think I was at {loc1}? Yeah, definitely {loc1}. Got there at {bell1}. I was on my phone most of the time. Looked up and it was already {bell2}.',
    'Where was I... right, {loc1}. From {bell1}. I was listening to a podcast. {bell2} came and went.',
    'I was at {loc1}. {bell1}. I think. Yeah, {bell1}. Left around {bell2}. My mind was elsewhere.',
    'Hard to say exactly. I was at {loc1} from about {bell1}. Time kind of disappeared. Next thing I knew it was {bell2}.',
    'I was zoned out at {loc1}. Got there at {bell1}. My brain was somewhere else entirely until {bell2}.',
    '{loc1}. From {bell1}. I was doom-scrolling most of the time. {bell2} caught me by surprise.',
    'I was at {loc1}, {bell1} to {bell2}. Honestly, I spent most of it staring at the wall thinking about nothing.',
    'I... was at {loc1}. Right. {bell1}. And then... {bell2}. Sorry, I\'m not great with details today.',

    // --- Professional / Precise (89–96) ---
    'I arrived at {loc1} at {bell1} to conduct a scheduled inspection. The inspection concluded at {bell2}.',
    'My assignment placed me at {loc1} from {bell1} to {bell2}. I completed the required task and documented it.',
    'I was at {loc1} from {bell1} through {bell2}, performing a routine security sweep.',
    'I arrived at {loc1} at precisely {bell1}. I departed at {bell2}. The interval was spent on standard duties.',
    'I was tasked with monitoring {loc1} from {bell1} to {bell2}. I carried out the task without deviation.',
    'My post was {loc1}. Shift start: {bell1}. Shift end: {bell2}. Activity: perimeter check. Status: complete.',
    'I was at {loc1} from {bell1} performing maintenance checks. Work concluded at {bell2}.',
    'I reported to {loc1} at {bell1} as scheduled. I was on-site through {bell2}.',

    // --- Reflective / Contemplative (97–100) ---
    'I was at {loc1}. Got there at {bell1}. Sat there thinking about nothing until {bell2}. One of those days.',
    'Funny how time works in this building. I was at {loc1} from {bell1}. Felt like five minutes. It was {bell2} when I checked.',
    '{loc1}, {bell1} to {bell2}. I remember the fluorescent lights buzzing. That\'s about all that happened.',
    'I was at {loc1}. {bell1} came and went. So did {bell2}. I was just... there.',
  ],

  // ─── Horn/Alarm Templates (15) ────────────────────────────
  hornTemplates: [
    'I heard the fire alarm test from {loc} at {bell}.',
    'The alarm check at {loc} went off at {bell}. I\'m sure of it.',
    'At {bell}, the alert from {loc} came through on my radio.',
    'There was an alarm test from {loc} at {bell}. Pretty loud.',
    'I heard the test alarm from {loc} at {bell}. Standard monthly check.',
    'The alarm at {loc} sounded at {bell}. I made a note of it.',
    'At {bell}, the alarm from {loc} went off. Brief — just a test.',
    '{bell}. Alarm from {loc}. Lasted about ten seconds.',
    'I heard the alarm from {loc} at {bell}. Startled me.',
    'The fire alarm test from {loc} at {bell}. You could hear it from anywhere.',
    'At {bell}, the alarm at {loc} was triggered for testing. Confirmed by radio.',
    'The alarm from {loc} at {bell} was the scheduled test. I remember checking.',
    'I caught the alarm from {loc} at {bell}. Hard to miss.',
    'At {bell}, the test alarm from {loc} sounded. Everyone heard it.',
    'The alarm at {loc} went off right at {bell}. I looked at my watch to confirm.',
  ],

  // ─── Relic / Object Templates (15) ─────────────────────────
  relicTemplates: [
    'I had {relic} with me the entire shift.',
    '{Relic} was on me — didn\'t let it out of my sight.',
    'All day, {relic} stayed in my possession. Standard protocol.',
    '{Relic} was in my pocket. I checked it twice.',
    'I had {relic}. It was assigned to me for the day.',
    '{Relic} was with me from clocking in to clocking out.',
    'I was carrying {relic}. It\'s logged to my name.',
    '{Relic} didn\'t leave my person. That\'s SOP.',
    'Yeah, {relic} was mine today. It was in my bag.',
    'I had {relic} on me. You can check the checkout log.',
    '{Relic} was assigned to me. I kept it secure.',
    'I was responsible for {relic} all day. It was in my possession.',
    '{Relic} was in my jacket pocket. Never set it down.',
    'I had {relic}. It was issued to me at the start of shift.',
    '{Relic} was with me throughout. I signed for it.',
  ],

  // ─── Scent Templates (15) ──────────────────────────────────
  scentTemplates: [
    'You could definitely smell {scent} at {loc}. Hard to miss.',
    'I noticed {scent} around {loc}.',
    'At {loc}, the air had that {scent} thing going on.',
    '{scent} at {loc}. Yeah, it was strong.',
    'The smell of {scent} at {loc} was pretty obvious.',
    'I noticed {scent} the second I walked into {loc}.',
    '{loc} smelled like {scent}. Not subtle.',
    'There was definitely {scent} at {loc}. Hit you right away.',
    'At {loc}, I could smell {scent}. It was everywhere.',
    '{scent} at {loc}. I remember because it made my eyes water.',
    'The {scent} at {loc} was strong enough to taste.',
    'You couldn\'t be in {loc} without noticing {scent}.',
    'At {loc}, {scent} was the dominant smell. Unmistakable.',
    'I smelled {scent} at {loc}. Lingered in my clothes after.',
    '{scent} at {loc}. First thing you notice walking in.',
  ],

  // ─── Environment Descriptors (20) ─────────────────────────
  environmentDescriptors: [
    'The ventilation at {loc} was running all morning',
    'Fluorescent lights buzzed at {loc}',
    'The smell of {scent} was noticeable at {loc}',
    'The HVAC at {loc} kept the temperature below normal',
    'The overhead lights at {loc} were flickering intermittently',
    'A draft from the stairwell kept {loc} cold all day',
    'The air at {loc} was stale and smelled of {scent}',
    'Water stains had appeared on the ceiling at {loc}',
    'The vending machines at {loc} hummed loudly',
    'The temperature at {loc} was noticeably warmer than usual',
    'Construction noise was audible from {loc}',
    'The motion-sensor lights at {loc} kept turning off',
    'There was a persistent smell of {scent} at {loc}',
    'The fire exit door near {loc} was propped open all morning',
    'The elevator near {loc} was out of service',
    'A cleaning crew had recently been through {loc}',
    'The air conditioning at {loc} was running on high',
    'There was {scent} in the air at {loc}, from a spill nearby',
    'The hallway near {loc} was being repainted',
    'An industrial fan was running at {loc}, circulating {scent}',
  ],

  // ─── Opening Templates (25) ───────────────────────────────
  openingTemplates: [
    'Look, it was a normal day. I was around {loc} most of the time.',
    'Nothing special happened. I was at {loc}.',
    'I was handling my usual business at {loc}. That\'s it.',
    'I\'ve got nothing to hide. I was at {loc}, doing my job.',
    'Standard day. I was at {loc}.',
    'My shift had me at {loc}. Nothing out of the ordinary.',
    'I was at {loc}. Same as always.',
    'I spent most of my time at {loc}. Pretty routine.',
    'I was working at {loc}. That\'s really all there is to it.',
    'Just another day. I was at {loc}.',
    'I was at {loc}, handling my regular duties.',
    'My day was at {loc}. Not much to tell.',
    'I was assigned to {loc}. Did what I was supposed to.',
    'Nothing unusual. I was at {loc} all day.',
    'I was based at {loc}. Normal operations.',
    'I was at {loc}. Can we make this quick?',
    'My workstation was at {loc}. I was there most of the day.',
    'I was at {loc}, going through the usual checklist.',
    'Pretty standard day at {loc}. Nothing happened.',
    'I was posted at {loc}. Quiet shift.',
    'I was at {loc}, doing paperwork mostly.',
    'They had me at {loc}. I did my job. That\'s it.',
    'I was at {loc}. If there\'s a problem, it didn\'t involve me.',
    'I was working out of {loc}. Regular duties.',
    'Just doing my thing at {loc}. Nothing to report.',
  ],

  // ─── Bell Probe Templates (25) ────────────────────────────
  bellTemplates: [
    'At {bell}, I was at {loc}. I remember checking my phone.',
    'When {bell} hit, I was at {loc}. Positive.',
    '{bell} — I was at {loc}, doing my rounds.',
    'I was at {loc} at {bell}. Checked the time on the wall clock.',
    'At {bell}, I was at {loc}. I had just refilled my coffee.',
    '{bell} found me at {loc}. I was going through emails.',
    'I was at {loc} at {bell}. My phone shows I sent a text from there.',
    'At {bell}? {loc}. Definitely {loc}.',
    'When it was {bell}, I was at {loc}. I\'m sure.',
    '{bell}, I was at {loc}. I remember the hallway was empty.',
    'I was at {loc} at {bell}. I had been there for a while.',
    'At {bell}, I was sitting at {loc}. Hadn\'t moved.',
    '{bell} — yeah, {loc}. I was on my break.',
    'At {bell}, I was at {loc}. I looked at the clock right around then.',
    'I can tell you exactly: {bell}, {loc}. I was watching the monitors.',
    '{bell} had me at {loc}. Standard.',
    'At {bell}, I was at {loc}. Doing inventory.',
    'I was at {loc} when {bell} came around. I noticed the time.',
    'At {bell}, {loc}. I was organizing files.',
    '{bell} — I hadn\'t left {loc} yet. Still working.',
    'At {bell}, I was at {loc}. The AC was loud.',
    'I was at {loc} at {bell}. My badge scan would show that.',
    'At {bell}, I was in {loc}. Quiet. Nobody around.',
    '{bell} had me at {loc}. I was finishing up a report.',
    'At {bell}, I was at {loc}. Just hanging back.',
  ],

  bellDeflection: 'I\'ve already given my times.',

  // ─── Route Probe Templates (20) ───────────────────────────
  routeTemplates: [
    'I went from {loc1} to {loc2}, left at {bell1}, arrived by {bell2}.',
    'Took the route from {loc1} to {loc2} — {bell1} through {bell2}.',
    'Between {loc1} and {loc2}, {bell1} to {bell2}. Nothing to report.',
    'I left {loc1} at {bell1} and got to {loc2} by {bell2}.',
    'From {loc1} to {loc2}. Departed {bell1}, arrived {bell2}.',
    'I walked from {loc1} at {bell1} to {loc2}. Got there at {bell2}.',
    '{bell1}: left {loc1}. {bell2}: reached {loc2}.',
    'I headed from {loc1} to {loc2} at {bell1}. Made it there by {bell2}.',
    'Traveled from {loc1} to {loc2}, starting at {bell1}. Arrived at {bell2}.',
    'I went from {loc1} at {bell1}. Reached {loc2} at {bell2}.',
    '{loc1} to {loc2}. Left at {bell1}. Arrived {bell2}. Took the back way.',
    'I was heading from {loc1} to {loc2}. {bell1} to {bell2}. Used the stairs.',
    'I left {loc1} at {bell1} for {loc2}. Got there at {bell2}.',
    'From {loc1}, I went to {loc2}. Departed {bell1}, arrived {bell2}.',
    'My route was {loc1} to {loc2}. Left at {bell1}, there by {bell2}.',
    'I went from {loc1} to {loc2}, {bell1} to {bell2}. Elevator was slow.',
    '{loc1} to {loc2}. I left at {bell1} and arrived at {bell2}.',
    'I took the main corridor from {loc1} to {loc2}. {bell1} to {bell2}.',
    'Departed {loc1} at {bell1}. Arrived {loc2} at {bell2}.',
    'From {loc1} at {bell1}, I went to {loc2}. Arrived {bell2}.',
  ],

  // ─── Anchor Probe Templates (15) ──────────────────────────
  anchorTemplates: [
    'I heard the alarm test from {loc} at {bell}. Clear as day.',
    'The test alert at {bell} from {loc}. I clocked it.',
    'At {bell}, the alarm from {loc} went off. I heard it.',
    'Yeah, the alarm from {loc} at {bell}. Everyone heard that.',
    'The fire alarm test — {loc}, {bell}. I remember.',
    'I heard it. The alarm from {loc}. At {bell}.',
    'At {bell}, the alarm from {loc} sounded. I made a note.',
    'The test alarm from {loc} at {bell}. Pretty standard.',
    '{bell}. The alarm from {loc}. You couldn\'t miss it.',
    'I was aware of the alarm from {loc} at {bell}. It\'s loud.',
    'The alarm from {loc} went off at {bell}. I checked my watch.',
    'At {bell}, the alarm test from {loc} — yeah, I heard it.',
    'The fire alarm at {loc} at {bell}. Brief but loud.',
    'I heard the alarm. From {loc}. At {bell}. That\'s confirmed.',
    'At {bell}, the alarm from {loc} sounded. Standard test.',
  ],

  anchorNone: 'I didn\'t catch the alarm test.',

  // ─── Object Probe Templates (15) ──────────────────────────
  objectTemplates: [
    'I had {relic} with me all day. Never put it down.',
    '{relic} was on my person. That\'s protocol.',
    'Yeah, {relic} was in my bag. All day.',
    'I was carrying {relic}. It\'s checked out to me.',
    '{relic} didn\'t leave my possession. I\'m sure.',
    'I had {relic}. Kept it in my pocket.',
    '{relic} was with me. I signed for it this morning.',
    'I had {relic} on me. Standard procedure.',
    '{relic} was in my jacket. Stayed there all shift.',
    'Yes, I had {relic}. It\'s still with me.',
    '{relic} was assigned to me. I kept it secure.',
    'I can confirm {relic} was in my possession.',
    '{relic} was on my person. You can check the log.',
    'I had {relic}. Didn\'t set it down once.',
    '{relic} — yes, it was with me. I\'m responsible for it.',
  ],

  objectNone: 'I wasn\'t carrying anything notable.',

  // ─── Sense Probe Templates (15) ───────────────────────────
  senseTemplates: [
    'Definitely smelled {scent} at {loc}. Couldn\'t miss it.',
    'I noticed {scent} at {loc}. Stuck with me.',
    'At {loc}, there was {scent}. Pretty strong.',
    '{scent} at {loc}. Yeah, I noticed.',
    'The smell of {scent} at {loc} was hard to ignore.',
    'I caught a whiff of {scent} at {loc}.',
    '{loc} smelled like {scent}. You couldn\'t not notice.',
    'At {loc}, {scent} was in the air. Definitely.',
    'I smelled {scent} at {loc}. First thing I noticed.',
    'There was {scent} at {loc}. It was strong.',
    '{scent} at {loc} — yeah, it was there.',
    'I noticed {scent} immediately at {loc}.',
    'At {loc}, the smell of {scent} was everywhere.',
    '{scent} was coming from somewhere at {loc}. I noticed it.',
    'The air at {loc} had {scent} in it. Unmistakable.',
  ],

  senseNone: 'Nothing stood out to me.',

  // ─── Witness Pool (20) ────────────────────────────────────
  witnessPool: [
    'a janitor', 'the lobby guard', 'a delivery driver', 'a security camera',
    'the receptionist', 'a maintenance tech', 'the front desk clerk', 'a courier',
    'the parking attendant', 'a cleaning crew member', 'the IT guy', 'a temp worker',
    'the facilities manager', 'a vendor rep', 'the elevator repairman', 'a building inspector',
    'the night security', 'a food delivery person', 'the mail room clerk', 'a visiting contractor',
  ],

  // ─── Witness Probe Templates (15) ─────────────────────────
  witnessTemplates: [
    '{witness} saw me near {loc}.',
    '{witness} was there when I passed {loc}. Ask them.',
    'Check with {witness}. They saw me at {loc}.',
    '{witness} can verify I was at {loc}.',
    'I ran into {witness} at {loc}. They\'ll remember.',
    '{witness} was nearby when I was at {loc}.',
    'Ask {witness} — they were at {loc} the same time I was.',
    '{witness} would have seen me at {loc}.',
    'I\'m pretty sure {witness} noticed me at {loc}.',
    '{witness} was working at {loc}. They saw me arrive.',
    'Talk to {witness}. They were at {loc} when I was.',
    '{witness} passed through {loc} while I was there.',
    'I saw {witness} at {loc}. They can confirm.',
    '{witness} can back me up. I was at {loc}.',
    '{witness} and I crossed paths at {loc}.',
  ],

  // ─── Consistency Templates (15) ───────────────────────────
  consistencyTemplates: [
    'My statement hasn\'t changed. Has theirs? Maybe you should double-check.',
    'Same answer as before. But have you compared it against what the others said? Interesting how they differ.',
    'I\'m consistent because I\'m telling the truth. Not everyone in this building can say that.',
    'You\'re spending a lot of time on me when you could be pressing someone whose story actually shifts.',
    'I told you what happened. It\'s the same story because it\'s what happened. Funny how that works.',
    'My account is solid. Press the others this hard and see what happens.',
    'Why would I change it? It\'s the truth. Try asking someone who has a reason to.',
    'You can run my statement against what you\'ve already heard. It\'ll match. Try that with theirs.',
    'Same story, same details, every time. That\'s what the truth sounds like. Lies sound different.',
    'I don\'t change my answers because I don\'t need to. Someone else in this building? Different story.',
    'Verified. Consistent. Accurate. Now go ask the person whose story keeps shifting.',
    'Ask me a hundred times. Same response. But notice who starts sweating when you ask them twice.',
    'My story checks out. The real question is whose doesn\'t.',
    'You\'re looking for inconsistencies? Wrong suspect. Spread the pressure around and see who flinches.',
    'I\'m not the one you should be circling back to. But that\'s your call.',
  ],

  // ─── Detail / Trap Probe Templates (20) ───────────────────
  detailPublicFlavor: [
    'The server room is a constant hum. Silence there is the abnormal thing.',
    'Keypads beep softly. You stop noticing until you can\'t.',
    'The garage has that stale concrete smell that sticks in your throat.',
    'Fluorescent lights buzz at a frequency that gets under your skin.',
    'The elevator takes forever between floors. You learn to use the stairs.',
    'The HVAC either runs too cold or not at all. No middle ground.',
    'Carpet tiles absorb sound. Your footsteps just... vanish.',
    'The break room always smells like microwaved leftovers. Always.',
    'The stairwell echoes. You hear footsteps two floors up without trying.',
    'The parking garage amplifies everything. A car door sounds like a gunshot.',
    'The lobby is all glass and marble. Cold in winter, hot in summer.',
    'Printer rooms smell like ozone and toner. You get used to it.',
    'The ceiling tiles are the same in every room. You start counting them.',
    'Cell signal drops in the basement. Everyone knows that.',
    'The vending machines hum louder at night. It\'s eerie if you\'re alone.',
    'The hallways all look the same. You navigate by floor numbers, not landmarks.',
    'Motion-sensor lights click on a half-second after you enter. It\'s unsettling.',
    'The loading dock smells like diesel and cardboard. Has for years.',
    'Sound carries in the open-plan sections. Privacy is a concept, not a reality.',
    'The fire exit doors are heavy. You feel them in your shoulders.',
  ],

  // ─── Filler / Neutral (25) ────────────────────────────────
  fillerNeutral: [
    'The building felt like it was running on backup power, emotionally speaking.',
    'People were performing normal. That\'s what made it weird.',
    'I remember thinking: don\'t be the last person alone in a hallway.',
    'Something was off. Not anything specific \u2014 just a vibe.',
    'I kept checking my phone. Not sure what I expected to find.',
    'Everyone was being a little too professional. You know what I mean?',
    'I found myself being careful about what I said. Can\'t explain why.',
    'The building has a rhythm. That day the rhythm was wrong.',
    'I noticed people avoiding eye contact more than usual.',
    'I was on edge. Just a feeling.',
    'I remember thinking: something here doesn\'t add up.',
    'The air felt charged. Like before a layoff announcement.',
    'I kept to myself more than usual. Seemed like the smart move.',
    'Everyone had somewhere to be. Nobody was lingering.',
    'I chose my words carefully. Something about the day called for it.',
    'Fluorescent lights have a way of making everything feel like an interrogation.',
    'I said what I needed to say. Nothing extra.',
    'There was a tension in the air. The kind you feel in your shoulders.',
    'I caught myself overthinking everything. That\'s not usually me.',
    'People were going through the motions. Efficiently. Almost too efficiently.',
    'I had this nagging feeling all day. Like I\'d forgotten something important.',
    'The silence in the building was louder than the HVAC. If that makes sense.',
    'I noticed I was holding my breath. More than once.',
    'I kept my head down. It seemed like the right play.',
    'That day had an energy to it. Not good, not bad. Just... alert.',
  ],

  // ─── Refusals (per temperament) ───────────────────────────
  refusals: {
    timid: 'I... look, there are things about that day I was told to keep quiet about. I\'m sorry, I just can\'t.',
    arrogant: 'That\'s above your clearance. You want motives \u2014 I can only give you movements.',
    annoyed: 'I\'ve been cooperative. But that touches on something beyond this investigation. Drop it.',
    talkative: 'Okay so \u2014 wait, no, I signed something about this. An NDA or... look, just ask me something else before I say too much.',
    clipped: 'I\'ll speak to my steps, not to my suspicions.',
    poetic: 'Some data points are redacted for a reason. I don\'t make that call.',
  },
  partialRefusalSuffix: 'But look, I was at {loc} at {bell}. That much I\'ll give you.',

  // ─── Rune Fact Phrasing ───────────────────────────────────
  anchorDescription: 'The fire alarm test sounded at {bell} from {loc}',
  roadFactTemplate: 'The route from {from} to {to} takes at least {bells} hour{s}.',
  roadFactNoShorter: 'Getting from {from} to {to} takes {bells} hour{s}. No shortcut exists.',
  relicHolderDesc: 'was checked out to one person only',
  relicLocationDesc: 'was logged at a single location',
  relicLocationFact: 'The item was last logged at {loc}.',
  envFactTemplate: 'Sensors at {loc} detected {scent} from {fromBell} through {toBell}.',
  hintPrefix: 'Analyst Note:',
  movementFactGate: 'From {from}, reaching {to} requires {bells} hour{s} minimum.',

  speakerMap: {
    'Marcus Cole': 'amit',
    'Elena Rivera': 'shreya',
    'Jay Chen': 'rohan',
    'Sofia Mercer': 'ishita',
    'Kwame Osei': 'dev',
    'Lin Zhao': 'ritu',
  },
};

export default casefileTemplates;
