import type { ThemeTemplates } from '../types.js';
import type { Bell, RuneArchetype, ContradictionType } from '../../types/index.js';

/**
 * Gaslight (Victorian Noir) — 100 alibi templates + expanded interrogation banks.
 *
 * Voice: Formal 1890s English. Carriages, gas lamps, calling cards, correspondence.
 * Social class inflects speech. Period-appropriate exclamations.
 */

const gaslightTemplates: ThemeTemplates = {
  // ─── Display names ─────────────────────────────────────────
  runeNames: {
    oaths: { name: 'Witness Statement', description: 'Testimonies, sworn accounts, timepieces' },
    roads: { name: 'Transit Record', description: 'Routes, carriages, footpaths, railways' },
    relics: { name: 'Evidence Log', description: 'Personal effects, belongings, instruments' },
    skies: { name: 'Scene Report', description: 'Atmosphere, conditions, sensory details' },
  } satisfies Record<RuneArchetype, { name: string; description: string }>,

  bellNames: {
    0: '8 AM',
    1: '9 AM',
    2: '10 AM',
    3: '11 AM',
    4: '12 PM',
    5: '1 PM',
  } satisfies Record<Bell, string>,

  bellLabelsShort: {
    0: '8a', 1: '9a', 2: '10a', 3: '11a', 4: '12p', 5: '1p',
  } satisfies Record<Bell, string>,

  contradictionLabels: {
    time: 'Timeline discrepancy',
    movement: 'Transit impossible',
    object: 'Evidence conflict',
    environment: 'Scene contradiction',
  } satisfies Record<ContradictionType, string>,

  // ─── 100 Alibi Templates ──────────────────────────────────
  alibiTemplates: [
    // --- Formal Testimony (1–10) ---
    'I was present at {loc1} from {bell1} until {bell2}. I spoke with no one during that interval. These are the facts as I recall them.',
    'I remained at {loc1} from {bell1} through {bell2}. The room was cold. I spoke to no one.',
    'From {bell1} until {bell2}, I was occupied at {loc1}. I had correspondence to attend to.',
    'I was at {loc1}. I arrived at {bell1} and departed after {bell2}. I can say no more than that.',
    'My presence at {loc1} from {bell1} to {bell2} is a matter of record. I trust that will suffice.',
    'I was within {loc1} from {bell1}. I did not leave until after {bell2}. The hour is not in question.',
    'From {bell1} to {bell2}, I remained at {loc1}. I attended to private matters of no concern to this inquiry.',
    'I give my word: I was at {loc1} from {bell1} until {bell2}. I have no reason to dissemble.',
    '{bell1} found me at {loc1}. I did not stir until {bell2}. That is the extent of my account.',
    'I was engaged at {loc1} from {bell1} until well past {bell2}. I kept no company during that time.',

    // --- Social Propriety / Class-conscious (11–20) ---
    'One does not discuss one\'s movements in such bald terms, but if you must know: {loc1}, from {bell1} until {bell2}.',
    'I find this line of questioning rather impertinent, but very well. I was at {loc1}. {bell1} to {bell2}. There.',
    'A lady does not account for her time to strangers, but given the circumstances — {loc1}. From {bell1}. Until {bell2}.',
    'I hardly think my whereabouts are any concern of yours, but I was at {loc1} from {bell1} through {bell2}. Is that quite enough?',
    'It is beneath my station to answer such questions. However: {loc1}. {bell1}. {bell2}. I trust you will record it accurately.',
    'I was at {loc1}, attending to household matters, from {bell1} to {bell2}. One does what is expected.',
    'The suggestion that I must justify my movements is frankly insulting. But for the record: {loc1}. {bell1} until {bell2}.',
    'I was about my business at {loc1}. The clock struck {bell1} as I began, and {bell2} as I finished. Quite proper.',
    'Upon my word, I was at {loc1} from {bell1}. I did not leave until {bell2}. I should not have to say it twice.',
    'I was at {loc1}. {bell1} to {bell2}. If my word is insufficient, I cannot imagine whose would satisfy.',

    // --- Servant / Lower-class deference (21–30) ---
    'Begging your pardon, sir, but I was at {loc1}. Cook sent me at {bell1} and I wasn\'t relieved until past {bell2}.',
    'I was about my duties at {loc1}, sir. From {bell1} until {bell2}. I kept my head down, as one does.',
    'If it please the inspector, I was at {loc1} from {bell1}. Didn\'t leave till {bell2}. I did what I was told.',
    'I was scrubbing the floors at {loc1}, sir. Started at {bell1}, wasn\'t done till {bell2}. My knees can testify.',
    'They put me at {loc1} at {bell1}. I stayed through {bell2}. Nobody told me different, so I stayed.',
    'I don\'t mean no trouble, sir. I was at {loc1}. {bell1} to {bell2}. That\'s where they said to be.',
    'I was polishing the silver at {loc1} from {bell1}. Mrs. Whitmore came to check at {bell2} and I was still at it.',
    'I was at {loc1}, sir, tending the fires. From {bell1} right through to {bell2}. The grates don\'t clean themselves.',
    'If you don\'t mind my saying, sir, I was at {loc1} the whole time. {bell1} to {bell2}. Honest.',
    'I was where I was told to be — {loc1}. From {bell1} till past {bell2}. I wouldn\'t dare leave my post.',

    // --- Weather / Atmospheric (31–42) ---
    'The rain was frightful. I left {loc1} at {bell1} with the intention of reaching {loc2} promptly, but the roads were rivers of mud. I arrived at {bell2}, drenched.',
    'Fog pressed against the windows of {loc1} all morning. I arrived at {bell1} and remained through {bell2}, watching the grey swallow the garden.',
    'The gas lamps at {loc1} cast their usual pallid glow. I sat beneath them from {bell1} to {bell2}, reading the correspondence.',
    'A bitter draught swept through {loc1} that morning. I endured it from {bell1} until {bell2}, when the fire was at last lit.',
    'The damp at {loc1} was pervasive — it seeped through everything. I was there from {bell1} to {bell2}, shivering the entire time.',
    'Rain drummed against the windows of {loc1} without ceasing. I was inside from {bell1} until {bell2}. The sound was maddening.',
    'The morning light at {loc1} was thin and grey — scarcely light at all. I arrived at {bell1} and did not leave until {bell2}.',
    'There was a cold mist hanging about {loc1} when I arrived at {bell1}. By {bell2}, it had not lifted. Neither had I.',
    'The chimneys of {loc1} were smoking badly that morning. I coughed through my time there — {bell1} to {bell2}.',
    'The frost on the panes of {loc1} was intricate, almost beautiful. I studied it from {bell1} until {bell2}.',
    'A persistent draught at {loc1} made the candles gutter all morning. I was there from {bell1} through {bell2}, re-lighting them.',
    'The wallpaper at {loc1} was peeling in the damp. I noticed it at {bell1} and was still noticing it at {bell2}. One has little else to observe.',

    // --- Professional / Duty (43–52) ---
    'I attended to matters at {loc1}, arriving at {bell1}. My business concluded around {bell2}. I keep careful records.',
    'My responsibilities required my presence at {loc1} from {bell1} until {bell2}. I discharged them without incident.',
    'I had an appointment at {loc1} at {bell1}. The matter extended until {bell2}. These things cannot be hurried.',
    'Duty called me to {loc1} at {bell1}. I remained there, engaged in professional matters, until {bell2}.',
    'I was conducting an inspection of {loc1} from {bell1}. The work was methodical and consumed the time until {bell2}.',
    'The accounts at {loc1} required my attention. I began at {bell1} and was still reconciling the figures at {bell2}.',
    'I was at {loc1} reviewing the household ledgers. {bell1} to {bell2}. The numbers do not add themselves.',
    'I had been summoned to {loc1} at {bell1} to address a matter of some urgency. I was not free to leave until {bell2}.',
    'Professional obligation placed me at {loc1} from {bell1} until {bell2}. I carry out my duties with precision.',
    'I was engaged in correspondence at {loc1}, beginning at {bell1}. The letters were many, and I did not finish until {bell2}.',

    // --- Journey / Transit (53–64) ---
    'I took the path from {loc1} to {loc2}, departing at {bell1}. The way was long, and I arrived by {bell2}.',
    'The journey from {loc1} to {loc2} occupied me from {bell1} to {bell2}. The roads were dreadful.',
    'I traveled from {loc1} to {loc2}, setting out at {bell1}. The cab delivered me by {bell2}.',
    'I walked from {loc1} toward {loc2} at {bell1}. The fog was impenetrable; I arrived only by {bell2}.',
    'At {bell1}, I departed {loc1} for {loc2}. I arrived precisely at {bell2}.',
    'At {bell1} I left {loc1}. By {bell2} I had reached {loc2}, somewhat the worse for weather.',
    'I took a hansom from {loc1} at {bell1}. The horse was slow and the driver slower. I reached {loc2} at {bell2}.',
    'The walk from {loc1} to {loc2} was disagreeable. I set out at {bell1} and arrived at {bell2}, my shoes ruined.',
    'I departed {loc1} at {bell1} on foot. The route to {loc2} was circuitous but I arrived by {bell2}.',
    'Between {loc1} and {loc2}, from {bell1} to {bell2}. The pavements were slick with rain.',
    'I went from {loc1} to {loc2}, beginning at {bell1}. The cold slowed my pace. I arrived at {bell2}.',
    'I took the long way from {loc1} to {loc2}. Departed at {bell1}, arrived at {bell2}. I had my reasons.',

    // --- Character voices (65–76) ---
    '{bell1}. {loc1}. I remained until {bell2}. If you require a more elaborate account, I suggest you consult someone with more patience.',
    'Position: {loc1}. Time of arrival: {bell1}. Time of departure: after {bell2}. No contact with other persons. Nothing to report.',
    'Well, I was at {loc1}, wasn\'t I, from {bell1} — the linens don\'t fold themselves — and I was still at it when {bell2} came and went.',
    'I remember quite clearly being at {loc1} when {bell1} struck. I remained there through {bell2}, going over the ledgers.',
    'I was at {loc1} from {bell1}. It is not a place I frequent willingly, but {bell2} found me there still.',
    'Good heavens, must we go through this again? {loc1}. From {bell1}. Until {bell2}. I was reading Trollope.',
    'I... well, if you must know, I was at {loc1}. From {bell1}. Until {bell2}. I was reading. There is nothing improper about reading.',
    'I was at {loc1} from {bell1} to {bell2}. I heard nothing. I saw nothing. I was entirely absorbed in my own affairs.',
    'The hours between {bell1} and {bell2} found me at {loc1}. I confess the time passed rather slowly.',
    'I took my rest at {loc1} from {bell1} to {bell2}. One must keep regular hours.',
    'I was in {loc1} from {bell1} to {bell2}. The walls are thin, but I heard nothing of consequence.',
    'I remained at {loc1}, reviewing the accounts, from {bell1} until well past {bell2}. Tedious but necessary.',

    // --- Irritable / Hostile (77–84) ---
    'I do not see why I should account for my movements, but if you insist: {loc1}. {bell1} to {bell2}. Now leave me be.',
    'This is tiresome. {loc1}. From {bell1}. Until {bell2}. I have nothing further to add, and I resent the implication.',
    'I was at {loc1}. {bell1}. {bell2}. If that is not sufficient, then nothing will be. Good day.',
    'Must I spell it out? {loc1}. {bell1} to {bell2}. I was alone and I was occupied. That is all.',
    'I have answered this question before and my answer has not changed. {loc1}. {bell1}. {bell2}.',
    'You are wasting my time, and I do not have an abundance of it. {loc1}. From {bell1} to {bell2}.',
    'I was at {loc1} from {bell1} until {bell2}. Now, is there anything else, or may I go?',
    'Frankly, I am insulted by this interrogation. {loc1}. {bell1} through {bell2}. My word should be sufficient.',

    // --- Chatty / Digressive (85–92) ---
    'Oh, well, you see, I was at {loc1} — arrived around {bell1}, I think — and the place was in the most dreadful state. I didn\'t leave until {bell2}, by which time I was quite exhausted.',
    'Let me think now... yes, I was at {loc1}. It must have been {bell1} when I arrived. And I stayed — well, I suppose until about {bell2}. Time does fly.',
    'Well, it\'s rather a long story, but the short version is: {loc1}. From {bell1}. I was there until {bell2}. There was a dead mouse in the corner, which was rather upsetting.',
    'I was at {loc1}, yes. {bell1} — no, wait. Yes, {bell1}. And I was still there at {bell2}. I remember because the clock chimed.',
    'Oh, where to begin? I was at {loc1} from {bell1}. The curtains needed attention, and the fire had gone out, and by the time I\'d sorted everything it was past {bell2}.',
    'Now then, I was at {loc1}. I got there at {bell1} — or was it just before? No, it was {bell1}. And I stayed right through until {bell2}. I had plenty to keep me busy.',
    'It was {bell1} when I found myself at {loc1}. I hadn\'t planned to stay, but one thing led to another and before I knew it, {bell2} had come and gone.',
    'I distinctly recall being at {loc1} at {bell1}. The grandfather clock was chiming — it\'s never quite right, you know — and I was still there when it chimed {bell2}.',

    // --- Reflective / Memory (93–100) ---
    'Looking back, I believe I was at {loc1} from {bell1} through {bell2}. The hours pass differently when one is lost in thought.',
    'My recollection places me at {loc1} from {bell1}. The next time I consulted my pocket watch, it read past {bell2}.',
    'I recall {loc1}. I recall {bell1}. I recall {bell2}. Between those hours, very little of interest occurred.',
    'The day is somewhat hazy in my memory, but I am certain of this: {loc1}. From {bell1}. Until {bell2}.',
    'I was at {loc1}. {bell1} came, and I was absorbed in my work. {bell2} came, and I had not noticed the hours passing.',
    'Memory is unreliable, but my pocket diary is not. It records my presence at {loc1} from {bell1} until {bell2}.',
    'I find myself returning, in memory, to {loc1}. I was there from {bell1} until {bell2}. The silence was remarkable.',
    'That morning — yes, I was at {loc1}. The clock struck {bell1} as I entered. It struck {bell2} before I thought to leave.',
  ],

  // ─── Horn/Clock Templates (15) ────────────────────────────
  hornTemplates: [
    'I heard the church bell toll from {loc} at {bell}.',
    'The clock at {loc} struck clearly — it was {bell}.',
    'At {bell}, the chimes from {loc} were unmistakable.',
    'The clock from {loc} sounded at {bell}. I am quite certain.',
    'I heard the chiming from {loc} at precisely {bell}.',
    'At {bell}, the bells of {loc} rang out. One could not miss them.',
    'The clock at {loc} struck {bell}. I checked my pocket watch to confirm.',
    'I was aware of the chimes from {loc} at {bell}. They carry well.',
    'At {bell}, the clock from {loc} sounded. A reassuring regularity.',
    'The hour was confirmed by the chimes from {loc} — it was {bell}.',
    'I heard {bell} strike from {loc}. The sound carried across the grounds.',
    'From {loc}, at {bell}, the clock struck. I recall it distinctly.',
    'The chimes from {loc} at {bell} interrupted my thoughts. Not unwelcome.',
    'At {bell}, I heard the clock from {loc}. It always rings true.',
    'The bells from {loc} sounded at {bell}. One becomes accustomed to them.',
  ],

  // ─── Relic / Object Templates (15) ─────────────────────────
  relicTemplates: [
    'I had {relic} on my person throughout the day.',
    '{Relic} was in my possession — I had not parted with it.',
    'Throughout the day, {relic} remained in my coat pocket.',
    '{Relic} was with me. I checked my pocket several times to be sure.',
    'I carried {relic} as is my habit. It did not leave my person.',
    '{Relic} was in my keeping. One does not misplace such things.',
    'I had {relic} about my person all day. I am most careful with valuables.',
    '{Relic} was mine to safeguard that day. I discharged the duty faithfully.',
    'I retained {relic} throughout. It was in my breast pocket.',
    '{Relic} was entrusted to me. It remained on my person at all times.',
    'I had {relic}. I am meticulous about such things.',
    '{Relic} did not leave my possession for a single moment.',
    'I bore {relic} with me. It is not the sort of thing one sets down carelessly.',
    '{Relic} was in my waistcoat pocket. I could feel its weight.',
    'All day, {relic} was in my care. I take such responsibilities seriously.',
  ],

  // ─── Scent Templates (15) ──────────────────────────────────
  scentTemplates: [
    'The air at {loc} reeked of {scent} — one could hardly mistake it.',
    'I distinctly recall {scent} about {loc}.',
    'At {loc}, the odour of {scent} was most pronounced.',
    '{scent} pervaded {loc}. It was quite overpowering.',
    'I noticed {scent} at {loc} immediately. Most disagreeable.',
    'The smell of {scent} hung about {loc}. Impossible to ignore.',
    'At {loc}, there was a strong scent of {scent}. I wrinkled my nose.',
    '{loc} carried the unmistakable odour of {scent}.',
    'I could not help but notice {scent} at {loc}. It was everywhere.',
    'The atmosphere at {loc} was thick with {scent}.',
    '{scent} at {loc} — yes, I recall it. Most pungent.',
    'One could smell {scent} at {loc} from the doorway.',
    'At {loc}, the air was heavy with {scent}. I remarked upon it at the time.',
    'The odour of {scent} at {loc} was the first thing I noticed upon entering.',
    '{scent} clung to everything at {loc}. My clothes still carry it.',
  ],

  // ─── Environment Descriptors (20) ─────────────────────────
  environmentDescriptors: [
    'A thick fog settled over {loc} that morning',
    'Gas lamps flickered weakly at {loc}',
    'The smell of {scent} pervaded {loc}',
    'Rain drummed steadily against the windows of {loc}',
    'A chill draught swept through {loc} without cease',
    'The fire at {loc} had gone out, leaving the room frigid',
    'Condensation ran down the windows of {loc}',
    'The gas jets at {loc} hissed and sputtered all morning',
    'A thin film of coal dust covered everything at {loc}',
    'The curtains at {loc} were drawn, admitting little light',
    'Frost patterns decorated the windows of {loc}',
    'The air at {loc} was thick with the smell of {scent}',
    'A damp cold permeated every corner of {loc}',
    'The wallpaper at {loc} was peeling in the humidity',
    'Candle wax had pooled on the tables at {loc}',
    'The floorboards at {loc} creaked with every step',
    'A persistent smell of {scent} hung about {loc}',
    'The rooms at {loc} were dark despite the hour',
    'Smoke from the nearby chimneys drifted across {loc}',
    'The carpets at {loc} were damp and smelled of {scent}',
  ],

  // ─── Opening Templates (25) ───────────────────────────────
  openingTemplates: [
    'I went about my affairs as always. I was near {loc} for much of the day.',
    'The day was unremarkable. I spent my time about {loc}.',
    'I attended to matters at {loc}. Nothing unusual transpired.',
    'My conscience is clear. I was at {loc} and conducted my business.',
    'I was at {loc}, as I have already stated.',
    'My day was spent principally at {loc}. I have nothing to conceal.',
    'I was occupied at {loc}. The day proceeded without incident.',
    'A quiet day. I was at {loc}, attending to correspondence.',
    'I was about my business at {loc}. Nothing out of the ordinary.',
    'The day found me at {loc}. I discharged my duties as always.',
    'I was at {loc}. There is little more to say.',
    'My movements were entirely proper. I was at {loc}.',
    'I spent the better part of the day at {loc}.',
    'I had business at {loc}. It was conducted in the usual manner.',
    'The morning found me at {loc}. I remained there for some hours.',
    'I was at {loc}, and I do not see why that should be remarkable.',
    'My affairs kept me at {loc}. They were of a private nature.',
    'I was engaged at {loc}. The details are not pertinent.',
    'A perfectly ordinary day at {loc}. Nothing warrants suspicion.',
    'I was at {loc}. If that requires further explanation, I am at a loss.',
    'The day was cold and I was at {loc}. That is the sum of it.',
    'I had been at {loc} since the morning. A matter of routine.',
    'My presence at {loc} was entirely expected and unremarkable.',
    'I was at {loc}. The household can confirm as much.',
    'I attended to {loc} as my duties required.',
  ],

  // ─── Bell Probe Templates (25) ────────────────────────────
  bellTemplates: [
    'At {bell}, I was at {loc}. I recall the gas lamps were lit.',
    'When {bell} struck, I stood at {loc}. I am quite certain.',
    '{bell} found me at {loc}, attending to matters.',
    'I was within {loc} at {bell}. The hour is not in question.',
    'At {bell}, I was at {loc}. My pocket watch confirmed it.',
    'When {bell} sounded, I was occupied at {loc}.',
    '{bell} — I was at {loc}. I recall the fire was dying.',
    'At {bell}, I was at {loc}. I remember the clock chiming.',
    'I was at {loc} when {bell} struck. The sound echoed.',
    'At {bell}, my position was {loc}. I have no doubt.',
    '{bell} found me at {loc}. I was reading at the time.',
    'When the clock struck {bell}, I was at {loc}.',
    'At {bell}, I was at {loc}. I recall it clearly.',
    'I was within {loc} at {bell}. I had been there some time.',
    '{bell} — yes, I was at {loc}. The curtains were drawn.',
    'At {bell}, I remained at {loc}. I had no reason to leave.',
    'I was at {loc} when {bell} struck. I looked up from my work.',
    'At {bell}, I was at {loc}. The room was cold.',
    'When {bell} came, I was at {loc}. Seated by the window.',
    'I was at {loc} at {bell}. I consulted my watch to be sure.',
    '{bell} found me at {loc}. I was writing letters.',
    'At {bell}, I was within {loc}. The gas was turned low.',
    'I was present at {loc} at {bell}. I am quite definite on this point.',
    'At {bell}, I was at {loc}. I remember because the post arrived.',
    'When {bell} struck, {loc} was where you would have found me.',
  ],

  bellDeflection: 'I have accounted for my time.',

  // ─── Route Probe Templates (20) ───────────────────────────
  routeTemplates: [
    'I walked from {loc1} to {loc2}, departing at {bell1} and arriving by {bell2}.',
    'The route from {loc1} to {loc2} — I took it from {bell1} through {bell2}.',
    'Between {loc1} and {loc2}, from {bell1} to {bell2}. The way was clear.',
    'I left {loc1} at {bell1} for {loc2}. I arrived at {bell2}.',
    'I traveled from {loc1} to {loc2}, {bell1} to {bell2}. The weather was foul.',
    'I departed {loc1} at {bell1} and reached {loc2} by {bell2}.',
    'From {loc1} to {loc2}. I set out at {bell1} and arrived at {bell2}.',
    'I took the route from {loc1} to {loc2}, leaving at {bell1}. I arrived at {bell2}.',
    '{bell1} saw me depart {loc1}. {bell2} saw me arrive at {loc2}.',
    'I went from {loc1} to {loc2}. Departed {bell1}, arrived {bell2}.',
    'I walked from {loc1} at {bell1}. The road to {loc2} brought me there by {bell2}.',
    'Between {loc1} and {loc2}, I was in transit from {bell1} to {bell2}.',
    'I made my way from {loc1} to {loc2}, beginning at {bell1}, arriving at {bell2}.',
    'From {loc1} at {bell1}, I proceeded to {loc2}. I arrived at {bell2}.',
    'I traveled between {loc1} and {loc2}, from {bell1} through to {bell2}.',
    'I left {loc1} at {bell1} and walked to {loc2}. The journey concluded at {bell2}.',
    'My route took me from {loc1} at {bell1} to {loc2} by {bell2}.',
    'I departed {loc1} at {bell1}. {loc2} received me at {bell2}.',
    'The walk from {loc1} to {loc2} occupied me from {bell1} until {bell2}.',
    'From {loc1} to {loc2}, {bell1} to {bell2}. The pavements were wet.',
  ],

  // ─── Anchor Probe Templates (15) ──────────────────────────
  anchorTemplates: [
    'I heard the clock strike from {loc} at {bell}. It echoed through the halls.',
    'The chime sounded at {bell} from {loc}. I am certain of it.',
    'At {bell}, the clock from {loc} was perfectly audible.',
    'I heard the chimes from {loc} at {bell}. They were quite distinct.',
    'The clock at {loc} struck {bell}. I paused to note the hour.',
    'At {bell}, the bells from {loc} rang out. I heard them clearly.',
    'From {loc}, at {bell}, the clock chimed. There was no mistaking it.',
    'I recall the clock from {loc} striking {bell}. It has a distinctive tone.',
    'The chimes from {loc} at {bell} reached my ears. They always do.',
    'At {bell}, I heard the clock from {loc}. I checked my watch — it agreed.',
    'The clock from {loc} sounded at {bell}. A familiar sound.',
    '{bell}. The chimes from {loc}. I noted the hour.',
    'I was aware of the clock from {loc} at {bell}. One becomes attuned to it.',
    'From {loc}, at {bell}, the clock struck. I looked up from what I was doing.',
    'The bells of {loc} chimed at {bell}. I remember because I was counting.',
  ],

  anchorNone: 'I did not hear the clock clearly.',

  // ─── Object Probe Templates (15) ──────────────────────────
  objectTemplates: [
    'I had {relic} with me all day. It did not leave my person.',
    '{relic} was in my keeping, I assure you.',
    '{relic} was on my person throughout. I am quite particular about such things.',
    'I carried {relic} with me. It remained in my pocket.',
    '{relic} was in my possession. I checked it several times.',
    'Yes, {relic} was with me. I had been entrusted with it.',
    'I had {relic}. It was in my breast pocket, where it always is.',
    '{relic} — yes, I carried it. It is not something I would leave unattended.',
    'I retained {relic} on my person. It was secure at all times.',
    '{relic} was mine to carry. I did so without incident.',
    'I had {relic} about me. I am never careless with such items.',
    '{relic} was in my coat. I felt it with every movement.',
    'I can confirm {relic} was with me. I am meticulous.',
    '{relic} did not leave my person. I give you my word.',
    'All day, {relic} was in my keeping. I take such matters seriously.',
  ],

  objectNone: 'I carried nothing of particular note.',

  // ─── Sense Probe Templates (15) ───────────────────────────
  senseTemplates: [
    'The air at {loc} carried {scent}. Quite unmistakable.',
    'I distinctly recall {scent} at {loc}. It lingered.',
    'At {loc}, there was a strong scent of {scent}. I noticed it at once.',
    '{scent} at {loc} — yes, most pronounced. One could hardly miss it.',
    'I noticed {scent} at {loc}. It was quite pervasive.',
    'The odour of {scent} at {loc} was impossible to ignore.',
    'At {loc}, {scent} hung in the air. I recall it distinctly.',
    '{scent} was evident at {loc}. I remarked upon it.',
    'I could not help but notice {scent} at {loc}.',
    'The atmosphere at {loc} was characterized by {scent}.',
    '{scent} at {loc} was the first thing one noticed.',
    'At {loc}, the air carried a distinct note of {scent}.',
    'I recall {scent} at {loc}. It was rather strong.',
    'The scent of {scent} at {loc} was unmistakable.',
    '{loc} was permeated with the smell of {scent}.',
  ],

  senseNone: 'I noticed nothing out of the ordinary.',

  // ─── Witness Pool (20) ────────────────────────────────────
  witnessPool: [
    'a footman', 'the coachman', 'the scullery maid', 'a constable',
    'the gardener', 'the butler', 'a delivery boy', 'the charwoman',
    'a telegram boy', 'the cook', 'a lamplighter', 'the stable boy',
    'a passing tradesman', 'the housekeeper', 'a chimney sweep', 'the postman',
    'a flower seller', 'the night watchman', 'a cab driver', 'the bootblack',
  ],

  // ─── Witness Probe Templates (15) ─────────────────────────
  witnessTemplates: [
    'I was observed by {witness} near {loc}.',
    '{witness} passed me at {loc}. They can corroborate.',
    'Ask {witness} — they saw me at {loc}.',
    '{witness} was present when I was at {loc}.',
    'I recall {witness} near {loc}. They would have seen me.',
    '{witness} can confirm my presence at {loc}.',
    'I crossed paths with {witness} at {loc}.',
    '{witness} was about their duties at {loc} when I was there.',
    'I am certain {witness} noticed me at {loc}.',
    '{witness} passed through {loc} while I was present.',
    'If you require corroboration, {witness} saw me at {loc}.',
    '{witness} and I were both at {loc}. They will attest.',
    'I believe {witness} took note of my presence at {loc}.',
    '{witness} was at {loc}. We nodded in passing.',
    'You might ask {witness}. They were at {loc} when I was.',
  ],

  // ─── Consistency Templates (15) ───────────────────────────
  consistencyTemplates: [
    'My account stands, Inspector. But I dare say not every account in this house would survive such scrutiny.',
    'I do not retract. I do not amend. But one wonders whether the same can be said for all present.',
    'You circle back to me while someone in this household is weaving a far more fragile story.',
    'I spoke truthfully the first time. But between these walls, I am not the only one with something to hide.',
    'Press me if you wish. My statement is ironclad. But have you examined theirs as closely?',
    'I have nothing to add and nothing to change. Though I wonder if that can be said of everyone under this roof.',
    'The truth does not shift with the hour, Inspector. Unless one has reason to shift it.',
    'I have given my account honestly. The question is whether everyone else has done the same.',
    'My words have not changed because they need not. Falsehoods, however, require constant maintenance.',
    'I stand by every word. But do press the others as firmly \u2014 some of them will not hold up as well.',
    'Consistent, Inspector. Unwaveringly so. One wonders who in this house cannot say the same.',
    'You seem to want a different answer. I have only the one. Others, perhaps, have several.',
    'My account is the one constant in this shifting fog of testimony.',
    'Ask me again tomorrow. You will hear the same. Can everyone in this house make that promise?',
    'I am being honest with you, Inspector. I only wish I could say the same of everyone here.',
  ],

  // ─── Detail / Trap Probe Templates (20) ───────────────────
  detailPublicFlavor: [
    'Gaslight makes everyone look tired. Even the innocent.',
    'The library smells of dust and polish, and the chill never quite leaves.',
    'Carpet muffles steps until it suddenly doesn\u2019t.',
    'The walls there are thin. You can hear breathing through them.',
    'The gas jets hiss constantly. You stop hearing it after a while.',
    'Coal smoke hangs in the air no matter how often the windows are opened.',
    'The floorboards have a language of their own. Every room creaks differently.',
    'Old wallpaper holds the smell of decades. Damp, tobacco, candle wax.',
    'The clocks are always being fussed over, always adjusted, never quite satisfying anyone.',
    'Draughts run through this house like ghosts. You feel them before you find them.',
    'The mirrors here are old and slightly clouded. They give nothing back clearly.',
    'Candlelight is kinder than gaslight. Neither is kind enough.',
    'The stairs announce every arrival. Discretion is impossible.',
    'The service chimes are tuned differently. You can tell which room is calling.',
    'Damp rises through the foundations. The lower rooms always feel cold.',
    'The house settles at night. Every joint and timber shifts.',
    'Paint peels in the damp rooms. It has for years.',
    'The corridors are narrow enough to brush both walls with your elbows.',
    'Silverware tarnishes quickly in this house. The air is to blame.',
    'The drawing room holds heat, but the study never does.',
  ],

  // ─── Filler / Neutral (25) ────────────────────────────────
  fillerNeutral: [
    'The house does that thing where it sounds occupied even when it isn\u2019t.',
    'Everyone was polite in the way people get when they\u2019re afraid.',
    'I kept catching myself listening for footsteps that never came.',
    'There was a tension in the household. Unspoken, but palpable.',
    'I chose my words carefully that day. More carefully than usual.',
    'The silence in the house felt deliberate. As if the walls were holding their breath.',
    'I recall feeling watched, though I cannot say by whom.',
    'One becomes attuned to the mood of a household. That day, the mood was wrong.',
    'I kept my counsel. It seemed the wise course.',
    'The servants were whispering. They stopped when I entered.',
    'I found myself being more cautious than usual. Pure instinct.',
    'The air had a quality \u2014 not a smell, exactly. An expectation.',
    'I was on edge. I could not tell you precisely why.',
    'The household runs on routine. That day, the routine felt like armor.',
    'I remember thinking: someone in this house is not what they seem.',
    'The gaslight makes shadows of everything. One begins to distrust one\u2019s own eyes.',
    'I said less than I knew. A habit of caution, nothing more.',
    'There are days when the house feels like a stage. This was one of them.',
    'I recall a heaviness in the air. Not weather \u2014 something social.',
    'The staff were going about their duties with unusual efficiency. As if avoiding idle conversation.',
    'I kept my observations to myself. One learns discretion in a household like this.',
    'I was aware of being studied. Perhaps I imagined it.',
    'The day had a quality of performance about it. Everyone playing their part.',
    'One cannot live under this roof without developing a sense for trouble.',
    'I said what was asked of me. I did not volunteer more.',
  ],

  // ─── Refusals (per temperament) ───────────────────────────
  refusals: {
    timid: 'Please, Inspector... there are matters I was warned not to discuss. For my own safety, you understand.',
    arrogant: 'You overstep yourself. I will speak to my movements, not to my suspicions. That is all you shall have.',
    annoyed: 'I have cooperated fully. But that particular question touches on something I cannot discuss. Not without protection.',
    talkative: 'Well I \u2014 oh dear, I almost said \u2014 no, no, I really mustn\u2019t. Someone made me promise, you see, and I \u2014',
    clipped: 'That line of questioning is not safe. Ask what I did instead.',
    poetic: 'Some secrets keep the household standing. I\u2019ll not be the one to shake the foundations.',
  },
  partialRefusalSuffix: 'But I will tell you this: I was at {loc} at {bell}. That is all I am prepared to say.',

  // ─── Rune Fact Phrasing ───────────────────────────────────
  anchorDescription: 'The church clock struck at {bell} from {loc}',
  roadFactTemplate: 'The route from {from} to {to} requires no fewer than {bells} hour{s} by carriage.',
  roadFactNoShorter: 'The path from {from} to {to} spans {bells} hour{s}. No swifter passage exists.',
  relicHolderDesc: 'was in the possession of one person alone',
  relicLocationDesc: 'was observed at a single location',
  relicLocationFact: 'The item was last reported within {loc}.',
  envFactTemplate: 'The air at {loc} carried the odour of {scent} from {fromBell} through {toBell}.',
  hintPrefix: 'Inspector\'s Note:',
  movementFactGate: 'From {from}, the route to {to} requires {bells} hour{s} at minimum.',

  speakerMap: {
    'Inspector Graves': 'ashutosh',
    'Lady Ashworth': 'amelia',
    'Dr. Pemberton': 'ratan',
    'Miss Harlow': 'sophia',
    'Colonel Finch': 'aditya',
    'Mrs. Whitmore': 'tanya',
  },
};

export default gaslightTemplates;
