import type { ThemeConfig } from './types.js';
import casefileTemplates from './templates/casefile-templates.js';

const casefileTheme: ThemeConfig = {
  id: 'casefile',

  core: {
    locations: [
      'Rooftop Bar',
      'Parking Garage B2',
      'Room 412',
      'The Lobby',
      'Server Room',
      'Loading Dock',
    ],
    suspectNames: ['Marcus Cole', 'Elena Rivera', 'Jay Chen', 'Sofia Mercer', 'Kwame Osei', 'Lin Zhao'],
    suspectRoles: [
      'Head of Security',
      'Financial Analyst',
      'IT Administrator',
      'Building Manager',
      'Night Shift Lead',
      'Executive Assistant',
    ],
    relics: [
      'the master keycard',
      'the encrypted USB drive',
      'a burner phone',
      'the security badge',
      'the laptop bag',
      'the sealed envelope',
    ],
    scents: ['fresh coffee', 'cleaning solvent', 'cigarette smoke', 'printer ink', 'hand sanitizer', 'takeout food'],
  },

  templates: casefileTemplates,

  copy: {
    gameTitle: 'CASE FILE: ZERO',
    gameSubtitle: 'Modern procedural \u2022 Cold logic',
    oathTexts: [
      'Before the precinct closes this case, someone\'s story needs to break.',
      'The surveillance footage has gaps. One alibi doesn\'t check out.',
      'Internal Affairs flagged this. Someone in this building is lying.',
      'The timeline doesn\'t add up. One of these statements is fabricated.',
      'A discrepancy in the access logs. Someone is not being straight with us.',
    ],
    liarLabel: 'Subject Zero',
    drawSectionTitle: 'Case Files',
    drawPrompt: 'Access your first case file to begin',
    drawVerb: 'Access',
    drawNounPlural: 'case files',
    drawnLabel: 'Accessed',
    accuseVerb: 'Flag as Subject Zero',
    accusePrompt: 'Name the suspect.',
    accuseHoldText: 'Hold to submit your finding',
    hintLabel: 'Analyst Note',
    footerText: 'Case File: Zero \u2014 A daily mystery',
    microHookIcon: '\uD83D\uDCF1',
    microHookText: '0900. One statement doesn\'t add up.',
    welcomeToastText: 'Access 2 files. Flag Subject Zero.',
    verdictWin: 'CASE CLOSED',
    verdictLose: 'CASE COLD',
    verdictWinFlavor: 'Subject identified. Case resolved.',
    verdictLoseFlavor: 'Wrong call. Subject walks.',
    loadingText: 'Loading Case File',
    modeTransitionText: 'Loading Case File\u2026',
    switchModeConfirm: 'Resets current case. Continue?',
    interrogateLabel: 'Question',
    evidenceLabels: {
      time: 'Timeline mismatch',
      movement: 'Access violation',
      object: 'Item discrepancy',
      environment: 'Scene anomaly',
    },
    stampWin: 'Status: Resolved',
    stampMercy: 'Status: Partial',
    stampLose: 'Status: Cold',
    practiceButton: 'Load Another Case',
    tomorrowTease: 'The next Case File drops at 00:00 UTC.',
    tagline: 'Modern procedural \u2022 Cold logic',

    tutorialWelcomeTitle: 'Agent Briefing',
    tutorialWelcomeBody: 'Six persons of interest have submitted their statements. One is Subject Zero \u2014 and their story has inconsistencies.',
    groupLabel: 'the team',
    mapLabel: 'The Building',
    timePeriodLabel: 'time blocks',
    travelUnitShort: 'hr',
    howToPlayTitle: 'Field Manual',
    howToPlayReturnButton: 'Return to Case',
    storyIntro: 'Every day, six persons of interest must account for their movements across the building \u2014 a network of locations connected by corridors and elevators. Each submits their statement: where they went, what they carried, what they observed.',
    storyVillain: 'But one of them is Subject Zero \u2014 whose statement doesn\u2019t hold up against the data. Your task is to identify them before the case goes cold.',
  },

  visuals: {
    cssVars: {
      '--coven-bg': '#141820',
      '--coven-bg-deep': '#0c0f14',
      '--coven-surface': '#1c2030',
      '--coven-surface-light': '#252a3a',
      '--coven-gold': '#3b82f6',
      '--coven-gold-bright': '#60a5fa',
      '--coven-gold-dim': '#2563eb',
      '--coven-iron': '#6b7280',
      '--coven-crimson': '#dc2626',
      '--coven-crimson-bright': '#ef4444',
      '--coven-forest': '#1a2a2a',
      '--coven-forest-bright': '#22c55e',
      '--coven-ember': '#f59e0b',
      '--coven-parchment': '#e2e8f0',
      '--coven-text': '#cbd5e1',
      '--coven-ink': '#0f172a',
    },
    headingFont: '"JetBrains Mono", monospace',
    headingFontClass: 'font-jetbrains',
    headingDecFont: '"JetBrains Mono", monospace',
    headingDecFontClass: 'font-jetbrains',
    portraitStyle: 'casefile',
  },
};

export default casefileTheme;
