import type { ThemeConfig } from './types.js';
import gaslightTemplates from './templates/gaslight-templates.js';

const gaslightTheme: ThemeConfig = {
  id: 'gaslight',

  core: {
    locations: [
      'The Parlour',
      'Blackwood Library',
      'Carriage House',
      'The Conservatory',
      "Servants' Quarters",
      'Garden Pavilion',
    ],
    suspectNames: ['Inspector Graves', 'Lady Ashworth', 'Dr. Pemberton', 'Miss Harlow', 'Colonel Finch', 'Mrs. Whitmore'],
    suspectRoles: [
      'Lead Investigator',
      'Estate Mistress',
      'Family Physician',
      'Governess',
      'Retired Officer',
      'Head Housekeeper',
    ],
    relics: [
      'the ivory letter opener',
      'the brass pocket watch',
      'a monogrammed handkerchief',
      'the silver cigarette case',
      'the leather journal',
      'the glass medicine vial',
    ],
    scents: ['pipe tobacco', 'lavender soap', 'lamp oil', 'camphor', 'coal dust', 'rosewater'],
  },

  templates: gaslightTemplates,

  copy: {
    gameTitle: 'THE GASLIGHT DOSSIER',
    gameSubtitle: 'Victorian noir \u2022 Gaslit investigation',
    oathTexts: [
      'Before the inquest concludes, the deceiver must be named \u2014 or justice fails.',
      'The evidence is circumstantial, but one account does not hold.',
      'Scotland Yard has sent word. A liar sits among the witnesses.',
      'The coroner demands answers. One testimony is fabricated.',
      'A shadow falls over this household. One of them is lying.',
    ],
    liarLabel: 'The Deceiver',
    drawSectionTitle: 'Evidence Dossier',
    drawPrompt: 'Open your first dossier to begin',
    drawVerb: 'Open',
    drawNounPlural: 'dossiers',
    drawnLabel: 'Opened',
    accuseVerb: 'Identify as Deceiver',
    accusePrompt: 'Name the suspect.',
    accuseHoldText: 'Hold to file your accusation',
    hintLabel: "Inspector's Note",
    footerText: 'The Gaslight Dossier \u2014 A daily mystery',
    microHookIcon: '\uD83D\uDD6F',
    microHookText: 'Nine o\'clock. One testimony is false.',
    welcomeToastText: 'Open 2 dossiers. Name the Deceiver.',
    verdictWin: 'CASE CLOSED',
    verdictLose: 'CASE COLD',
    verdictWinFlavor: 'Justice is served.',
    verdictLoseFlavor: 'The deceiver walks free.',
    loadingText: 'Reviewing the Dossier',
    modeTransitionText: 'Assembling the Dossier\u2026',
    switchModeConfirm: 'Resets current case. Continue?',
    interrogateLabel: 'Question',
    evidenceLabels: {
      time: 'Timeline discrepancy',
      movement: 'Transit impossible',
      object: 'Evidence conflict',
      environment: 'Scene contradiction',
    },
    stampWin: 'Case File: Closed',
    stampMercy: 'Case File: Inconclusive',
    stampLose: 'Case File: Cold',
    practiceButton: 'Review Another Case',
    tomorrowTease: 'The next Case File opens at 00:00 UTC.',
    tagline: 'Victorian noir \u2022 Gaslit investigation',

    tutorialWelcomeTitle: 'Good Evening, Inspector',
    tutorialWelcomeBody: 'Six members of the household have given their accounts. One is the Deceiver \u2014 and their story will not withstand scrutiny.',
    groupLabel: 'the household',
    mapLabel: 'The Estate',
    timePeriodLabel: 'hours',
    travelUnitShort: 'hr',
    howToPlayTitle: "Investigator\u2019s Guide",
    howToPlayReturnButton: 'Back to the Investigation',
    storyIntro: 'Every day, six members of the household must account for their movements across the estate \u2014 a network of rooms and grounds connected by corridors. Each gives their account: where they went, what they handled, what they noticed.',
    storyVillain: 'But one of them is the Deceiver \u2014 a liar whose account doesn\u2019t hold up against the evidence. Your task is to identify them before the clock strikes midnight.',
  },

  visuals: {
    cssVars: {
      '--coven-bg': '#0d0d0d',
      '--coven-bg-deep': '#080808',
      '--coven-surface': '#1a1a1a',
      '--coven-surface-light': '#252525',
      '--coven-gold': '#c9a84c',
      '--coven-gold-bright': '#e8c96e',
      '--coven-gold-dim': '#8a7340',
      '--coven-iron': '#6b7280',
      '--coven-crimson': '#6b1d2a',
      '--coven-crimson-bright': '#9b2d3f',
      '--coven-forest': '#1a2a1a',
      '--coven-forest-bright': '#2e6d3a',
      '--coven-ember': '#8b6914',
      '--coven-parchment': '#d4c8b0',
      '--coven-text': '#c8bda8',
      '--coven-ink': '#1a1610',
    },
    headingFont: '"Playfair Display", Georgia, serif',
    headingFontClass: 'font-playfair',
    headingDecFont: '"Playfair Display", Georgia, serif',
    headingDecFontClass: 'font-playfair',
    portraitStyle: 'gaslight',
  },
};

export default gaslightTheme;
