import type { ThemeConfig } from './types.js';
import ledgerTemplates from './templates/ledger-templates.js';

const ledgerTheme: ThemeConfig = {
  id: 'ledger',

  core: {
    locations: [
      'The Ford',
      'Stone Gate',
      'Hall of Oaths',
      'Ash Grove',
      'Beacon Tower',
      "Warden's Rest",
    ],
    suspectNames: ['Mordecai', 'Isolde', 'Theron', 'Vesper', 'Rowena', 'Aldric'],
    suspectRoles: [
      'Warden of Leaves',
      'Keeper of the Ford',
      'Oath-scribe',
      'Stone Mason',
      'Bell Watcher',
      'Ash Gatherer',
    ],
    relics: [
      "the Warden's signet ring",
      'the iron key of the vault',
      'a shard of the broken oath-stone',
      'the silver bell of summoning',
      "the keeper's lantern",
      'the elder-rune tablet',
    ],
    scents: ['pine smoke', 'damp moss', 'iron rust', 'burnt cedar', 'wet stone', 'old parchment'],
  },

  templates: ledgerTemplates,

  copy: {
    gameTitle: 'THE LEDGER OF THE WATCH',
    gameSubtitle: 'Dark fantasy \u2022 Oaths & Runes',
    oathTexts: [
      'By the Third Bell, the Watch must name the Oathbreaker \u2014 or the covenant falls.',
      'Before the sun passes the watchtower, one among us must be condemned.',
      'The elder runes have spoken. A liar walks among the sworn.',
      'The seals are broken. One oath was false. The Watch demands truth.',
      'An oathbreaker hides in plain sight. The runes will reveal the truth.',
    ],
    liarLabel: 'Oathbreaker',
    drawSectionTitle: 'Runes of the Elders',
    drawPrompt: 'Draw your first rune to begin',
    drawVerb: 'Draw',
    drawNounPlural: 'runes',
    drawnLabel: 'Drawn',
    accuseVerb: 'Name as Oathbreaker',
    accusePrompt: 'Speak the name.',
    accuseHoldText: 'Hold to seal your accusation',
    hintLabel: 'Law of Stone',
    footerText: 'The Ledger of the Watch \u2014 A daily mystery',
    microHookIcon: '\uD83C\uDFBA',
    microHookText: 'Second Bell. One oath is broken.',
    welcomeToastText: 'Draw 2 runes. Name the Oathbreaker.',
    verdictWin: 'SURVIVED',
    verdictLose: 'FALLEN',
    verdictWinFlavor: 'The covenant endures.',
    verdictLoseFlavor: 'The covenant is broken.',
    loadingText: 'Consulting the Elder Runes',
    modeTransitionText: 'Rebinding the Case\u2026',
    switchModeConfirm: 'Resets current case. Continue?',
    interrogateLabel: 'Interrogate',
    evidenceLabels: {
      time: 'Bell contradiction',
      movement: 'Travel impossible',
      object: 'Relic mismatch',
      environment: 'Sense contradiction',
    },
    stampWin: 'Watch Record: Clean',
    stampMercy: 'Watch Record: Mercy',
    stampLose: 'Watch Record: Fallen',
    practiceButton: 'Consult Another Chronicle',
    tomorrowTease: 'The next Chronicle opens at 00:00 UTC.',
    tagline: 'Dark fantasy \u2022 Oaths & Runes',

    tutorialWelcomeTitle: 'Welcome, Watcher',
    tutorialWelcomeBody: 'Six sworn members of the Watch have given their alibis. One has broken their oath \u2014 the Oathbreaker.',
    groupLabel: 'the Watch',
    mapLabel: 'The Crossing',
    timePeriodLabel: 'bells',
    travelUnitShort: 'hr',
    howToPlayTitle: "Watcher\u2019s Codex",
    howToPlayReturnButton: 'Return to the Watch',
    storyIntro: 'Every day, six sworn members of the Watch must account for their movements across The Crossing \u2014 a network of locations connected by roads. Each tells their alibi: where they went, what they carried, what they sensed.',
    storyVillain: 'But one of them is the Oathbreaker \u2014 a liar whose story doesn\u2019t hold up against the truth. Your task is to find them before the Third Bell tolls.',
  },

  visuals: {
    cssVars: {
      '--coven-bg': '#1a1625',
      '--coven-bg-deep': '#211c30',
      '--coven-surface': '#252040',
      '--coven-surface-light': '#302a4a',
      '--coven-gold': '#c4a35a',
      '--coven-gold-bright': '#e8c96e',
      '--coven-gold-dim': '#8a7340',
      '--coven-iron': '#6b7280',
      '--coven-crimson': '#8b1a1a',
      '--coven-crimson-bright': '#c62828',
      '--coven-forest': '#1a3a2a',
      '--coven-forest-bright': '#2e7d4a',
      '--coven-ember': '#b45309',
      '--coven-parchment': '#e8dcc8',
      '--coven-text': '#e4daca',
      '--coven-ink': '#2a1f0e',
    },
    headingFont: '"Cinzel", serif',
    headingFontClass: 'font-cinzel',
    headingDecFont: '"Cinzel Decorative", serif',
    headingDecFontClass: 'font-cinzel-dec',
    portraitStyle: 'fantasy',
  },
};

export default ledgerTheme;
